
import { RegionDict, RegionLevel, DictStatus } from '../types';

const now = new Date().toISOString();

export const INITIAL_REGIONS: RegionDict[] = [
  // Country
  { regionId: 'cn', regionName: '中国', regionCode: 'CN', regionLevel: RegionLevel.COUNTRY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Regions
  { regionId: 'hd', parentId: 'cn', regionName: '华东地区', regionCode: 'HD', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hn', parentId: 'cn', regionName: '华南地区', regionCode: 'HN', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hb', parentId: 'cn', regionName: '华北地区', regionCode: 'HB', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz', parentId: 'cn', regionName: '华中地区', regionCode: 'HZ', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xn', parentId: 'cn', regionName: '西南地区', regionCode: 'XN', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xb', parentId: 'cn', regionName: '西北地区', regionCode: 'XB', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'db', parentId: 'cn', regionName: '东北地区', regionCode: 'DB', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gat', parentId: 'cn', regionName: '特别行政区', regionCode: 'GAT', regionLevel: RegionLevel.REGION, status: DictStatus.ENABLED, isSystem: true, createTime: now },

  // Provinces - 华东地区
  { regionId: 'sh', parentId: 'hd', regionName: '上海市', regionCode: '310000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'js', parentId: 'hd', regionName: '江苏省', regionCode: '320000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zj', parentId: 'hd', regionName: '浙江省', regionCode: '330000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ah', parentId: 'hd', regionName: '安徽省', regionCode: '340000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fj', parentId: 'hd', regionName: '福建省', regionCode: '350000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jx', parentId: 'hd', regionName: '江西省', regionCode: '360000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sd', parentId: 'hd', regionName: '山东省', regionCode: '370000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 华南地区
  { regionId: 'gd', parentId: 'hn', regionName: '广东省', regionCode: '440000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gx', parentId: 'hn', regionName: '广西壮族自治区', regionCode: '450000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hi', parentId: 'hn', regionName: '海南省', regionCode: '460000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 华北地区
  { regionId: 'bj', parentId: 'hb', regionName: '北京市', regionCode: '110000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tj', parentId: 'hb', regionName: '天津市', regionCode: '120000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'he', parentId: 'hb', regionName: '河北省', regionCode: '130000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sx', parentId: 'hb', regionName: '山西省', regionCode: '140000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nm', parentId: 'hb', regionName: '内蒙古自治区', regionCode: '150000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 华中地区
  { regionId: 'henan', parentId: 'hz', regionName: '河南省', regionCode: '410000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hubei', parentId: 'hz', regionName: '湖北省', regionCode: '420000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hunan', parentId: 'hz', regionName: '湖南省', regionCode: '430000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 西南地区
  { regionId: 'cq', parentId: 'xn', regionName: '重庆市', regionCode: '500000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sc', parentId: 'xn', regionName: '四川省', regionCode: '510000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gz', parentId: 'xn', regionName: '贵州省', regionCode: '520000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yn', parentId: 'xn', regionName: '云南省', regionCode: '530000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xz', parentId: 'xn', regionName: '西藏自治区', regionCode: '540000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 西北地区
  { regionId: 'shaanxi', parentId: 'xb', regionName: '陕西省', regionCode: '610000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gs', parentId: 'xb', regionName: '甘肃省', regionCode: '620000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qh', parentId: 'xb', regionName: '青海省', regionCode: '630000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nx', parentId: 'xb', regionName: '宁夏回族自治区', regionCode: '640000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xj', parentId: 'xb', regionName: '新疆维吾尔自治区', regionCode: '650000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 东北地区
  { regionId: 'ln', parentId: 'db', regionName: '辽宁省', regionCode: '210000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jl', parentId: 'db', regionName: '吉林省', regionCode: '220000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hlj', parentId: 'db', regionName: '黑龙江省', regionCode: '230000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Provinces - 特别行政区
  { regionId: 'hk', parentId: 'gat', regionName: '香港特别行政区', regionCode: '810000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mo', parentId: 'gat', regionName: '澳门特别行政区', regionCode: '820000', regionLevel: RegionLevel.PROVINCE, status: DictStatus.ENABLED, isSystem: true, createTime: now },

  // Cities - 华东地区
  { regionId: 'sh_c', parentId: 'sh', regionName: '上海市', regionCode: '310100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 江苏省
  { regionId: 'nj', parentId: 'js', regionName: '南京市', regionCode: '320100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wx', parentId: 'js', regionName: '无锡市', regionCode: '320200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xz', parentId: 'js', regionName: '徐州市', regionCode: '320300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz', parentId: 'js', regionName: '常州市', regionCode: '320400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz_js', parentId: 'js', regionName: '苏州市', regionCode: '320500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nt', parentId: 'js', regionName: '南通市', regionCode: '320600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lyg', parentId: 'js', regionName: '连云港市', regionCode: '320700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ha', parentId: 'js', regionName: '淮安市', regionCode: '320800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yc_js', parentId: 'js', regionName: '盐城市', regionCode: '320900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yz_js', parentId: 'js', regionName: '扬州市', regionCode: '321000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zj_js', parentId: 'js', regionName: '镇江市', regionCode: '321100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tz', parentId: 'js', regionName: '泰州市', regionCode: '321200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sq', parentId: 'js', regionName: '宿迁市', regionCode: '321300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 浙江省
  { regionId: 'hz_c', parentId: 'zj', regionName: '杭州市', regionCode: '330100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nb', parentId: 'zj', regionName: '宁波市', regionCode: '330200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wz', parentId: 'zj', regionName: '温州市', regionCode: '330300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jx', parentId: 'zj', regionName: '嘉兴市', regionCode: '330400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz_zj', parentId: 'zj', regionName: '湖州市', regionCode: '330500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sx', parentId: 'zj', regionName: '绍兴市', regionCode: '330600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jh', parentId: 'zj', regionName: '金华市', regionCode: '330700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qz', parentId: 'zj', regionName: '衢州市', regionCode: '330800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zs', parentId: 'zj', regionName: '舟山市', regionCode: '330900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tz_zj', parentId: 'zj', regionName: '台州市', regionCode: '331000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ls', parentId: 'zj', regionName: '丽水市', regionCode: '331100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 安徽省
  { regionId: 'hf', parentId: 'ah', regionName: '合肥市', regionCode: '340100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wh_ah', parentId: 'ah', regionName: '芜湖市', regionCode: '340200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bb', parentId: 'ah', regionName: '蚌埠市', regionCode: '340300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hn_ah', parentId: 'ah', regionName: '淮南市', regionCode: '340400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mas', parentId: 'ah', regionName: '马鞍山市', regionCode: '340500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hb_ah', parentId: 'ah', regionName: '淮北市', regionCode: '340600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tl', parentId: 'ah', regionName: '铜陵市', regionCode: '340700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'aq', parentId: 'ah', regionName: '安庆市', regionCode: '340800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hs', parentId: 'ah', regionName: '黄山市', regionCode: '341000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_ah', parentId: 'ah', regionName: '滁州市', regionCode: '341100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fy', parentId: 'ah', regionName: '阜阳市', regionCode: '341200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz_ah', parentId: 'ah', regionName: '宿州市', regionCode: '341300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'la', parentId: 'ah', regionName: '六安市', regionCode: '341500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bz', parentId: 'ah', regionName: '亳州市', regionCode: '341600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_ah2', parentId: 'ah', regionName: '池州市', regionCode: '341700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xc', parentId: 'ah', regionName: '宣城市', regionCode: '341800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 福建省
  { regionId: 'fz', parentId: 'fj', regionName: '福州市', regionCode: '350100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xm', parentId: 'fj', regionName: '厦门市', regionCode: '350200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pt', parentId: 'fj', regionName: '莆田市', regionCode: '350300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sm', parentId: 'fj', regionName: '三明市', regionCode: '350400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qz_fj', parentId: 'fj', regionName: '泉州市', regionCode: '350500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zz_fj', parentId: 'fj', regionName: '漳州市', regionCode: '350600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'np', parentId: 'fj', regionName: '南平市', regionCode: '350700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ly', parentId: 'fj', regionName: '龙岩市', regionCode: '350800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nd', parentId: 'fj', regionName: '宁德市', regionCode: '350900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 江西省
  { regionId: 'nc', parentId: 'jx', regionName: '南昌市', regionCode: '360100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jdz', parentId: 'jx', regionName: '景德镇市', regionCode: '360200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'px', parentId: 'jx', regionName: '萍乡市', regionCode: '360300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jj', parentId: 'jx', regionName: '九江市', regionCode: '360400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xy_jx', parentId: 'jx', regionName: '新余市', regionCode: '360500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yt', parentId: 'jx', regionName: '鹰潭市', regionCode: '360600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gz', parentId: 'jx', regionName: '赣州市', regionCode: '360700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ja', parentId: 'jx', regionName: '吉安市', regionCode: '360800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yc_jx', parentId: 'jx', regionName: '宜春市', regionCode: '360900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fz_jx', parentId: 'jx', regionName: '抚州市', regionCode: '361000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sr', parentId: 'jx', regionName: '上饶市', regionCode: '361100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 山东省
  { regionId: 'jn', parentId: 'sd', regionName: '济南市', regionCode: '370100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qd', parentId: 'sd', regionName: '青岛市', regionCode: '370200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zb', parentId: 'sd', regionName: '淄博市', regionCode: '370300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zz_sd', parentId: 'sd', regionName: '枣庄市', regionCode: '370400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dy', parentId: 'sd', regionName: '东营市', regionCode: '370500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yt_sd', parentId: 'sd', regionName: '烟台市', regionCode: '370600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wf', parentId: 'sd', regionName: '潍坊市', regionCode: '370700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jn_sd', parentId: 'sd', regionName: '济宁市', regionCode: '370800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ta', parentId: 'sd', regionName: '泰安市', regionCode: '370900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wh_sd', parentId: 'sd', regionName: '威海市', regionCode: '371000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'rz', parentId: 'sd', regionName: '日照市', regionCode: '371100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ly_sd', parentId: 'sd', regionName: '临沂市', regionCode: '371300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dz', parentId: 'sd', regionName: '德州市', regionCode: '371400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lc', parentId: 'sd', regionName: '聊城市', regionCode: '371500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bz_sd', parentId: 'sd', regionName: '滨州市', regionCode: '371600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz_sd', parentId: 'sd', regionName: '菏泽市', regionCode: '371700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 华南地区
  // 广东省
  { regionId: 'gz_gd', parentId: 'gd', regionName: '广州市', regionCode: '440100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz_gd', parentId: 'gd', regionName: '深圳市', regionCode: '440300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zh', parentId: 'gd', regionName: '珠海市', regionCode: '440400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'st', parentId: 'gd', regionName: '汕头市', regionCode: '440500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fs', parentId: 'gd', regionName: '佛山市', regionCode: '440600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sg', parentId: 'gd', regionName: '韶关市', regionCode: '440200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zj_gd', parentId: 'gd', regionName: '湛江市', regionCode: '440800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zq', parentId: 'gd', regionName: '肇庆市', regionCode: '441200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jm', parentId: 'gd', regionName: '江门市', regionCode: '440700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mm', parentId: 'gd', regionName: '茂名市', regionCode: '440900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz_gd', parentId: 'gd', regionName: '惠州市', regionCode: '441300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mz', parentId: 'gd', regionName: '梅州市', regionCode: '441400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sw', parentId: 'gd', regionName: '汕尾市', regionCode: '441500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hy', parentId: 'gd', regionName: '河源市', regionCode: '441600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yj', parentId: 'gd', regionName: '阳江市', regionCode: '441700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qy', parentId: 'gd', regionName: '清远市', regionCode: '441800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dg', parentId: 'gd', regionName: '东莞市', regionCode: '441900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zs_gd', parentId: 'gd', regionName: '中山市', regionCode: '442000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_gd', parentId: 'gd', regionName: '潮州市', regionCode: '445100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jy', parentId: 'gd', regionName: '揭阳市', regionCode: '445200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yf', parentId: 'gd', regionName: '云浮市', regionCode: '445300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 广西壮族自治区
  { regionId: 'nn', parentId: 'gx', regionName: '南宁市', regionCode: '450100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lz_gx', parentId: 'gx', regionName: '柳州市', regionCode: '450200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gl', parentId: 'gx', regionName: '桂林市', regionCode: '450300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wz_gx', parentId: 'gx', regionName: '梧州市', regionCode: '450400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bh', parentId: 'gx', regionName: '北海市', regionCode: '450500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fcg', parentId: 'gx', regionName: '防城港市', regionCode: '450600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qz_gx', parentId: 'gx', regionName: '钦州市', regionCode: '450700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gg', parentId: 'gx', regionName: '贵港市', regionCode: '450800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yl', parentId: 'gx', regionName: '玉林市', regionCode: '450900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bs', parentId: 'gx', regionName: '百色市', regionCode: '451000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz_gx', parentId: 'gx', regionName: '贺州市', regionCode: '451100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hc', parentId: 'gx', regionName: '河池市', regionCode: '451200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lb', parentId: 'gx', regionName: '来宾市', regionCode: '451300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_gx', parentId: 'gx', regionName: '崇左市', regionCode: '451400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 海南省
  { regionId: 'haikou', parentId: 'hi', regionName: '海口市', regionCode: '460100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sanya', parentId: 'hi', regionName: '三亚市', regionCode: '460200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ss', parentId: 'hi', regionName: '三沙市', regionCode: '460300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dz_hai', parentId: 'hi', regionName: '儋州市', regionCode: '460400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 华北地区
  // 北京市
  { regionId: 'bj_c', parentId: 'bj', regionName: '北京市', regionCode: '110100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 天津市
  { regionId: 'tj_c', parentId: 'tj', regionName: '天津市', regionCode: '120100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 河北省
  { regionId: 'sjz', parentId: 'he', regionName: '石家庄市', regionCode: '130100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ts', parentId: 'he', regionName: '唐山市', regionCode: '130200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qhd', parentId: 'he', regionName: '秦皇岛市', regionCode: '130300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hd', parentId: 'he', regionName: '邯郸市', regionCode: '130400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xt', parentId: 'he', regionName: '邢台市', regionCode: '130500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bd', parentId: 'he', regionName: '保定市', regionCode: '130600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zjk', parentId: 'he', regionName: '张家口市', regionCode: '130700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cd', parentId: 'he', regionName: '承德市', regionCode: '130800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz', parentId: 'he', regionName: '沧州市', regionCode: '130900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lf', parentId: 'he', regionName: '廊坊市', regionCode: '131000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hs', parentId: 'he', regionName: '衡水市', regionCode: '131100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 山西省
  { regionId: 'ty', parentId: 'sx', regionName: '太原市', regionCode: '140100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dt', parentId: 'sx', regionName: '大同市', regionCode: '140200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yq', parentId: 'sx', regionName: '阳泉市', regionCode: '140300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_sx', parentId: 'sx', regionName: '长治市', regionCode: '140400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jc', parentId: 'sx', regionName: '晋城市', regionCode: '140500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz_sx', parentId: 'sx', regionName: '朔州市', regionCode: '140600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jz', parentId: 'sx', regionName: '晋中市', regionCode: '140700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yc_sx', parentId: 'sx', regionName: '运城市', regionCode: '140800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xz_sx', parentId: 'sx', regionName: '忻州市', regionCode: '140900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lf_sx', parentId: 'sx', regionName: '临汾市', regionCode: '141000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'll', parentId: 'sx', regionName: '吕梁市', regionCode: '141100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 内蒙古自治区
  { regionId: 'hhht', parentId: 'nm', regionName: '呼和浩特市', regionCode: '150100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bty', parentId: 'nm', regionName: '包头市', regionCode: '150200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wh_nm', parentId: 'nm', regionName: '乌海市', regionCode: '150300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cf', parentId: 'nm', regionName: '赤峰市', regionCode: '150400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tl', parentId: 'nm', regionName: '通辽市', regionCode: '150500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ordos', parentId: 'nm', regionName: '鄂尔多斯市', regionCode: '150600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hlbe', parentId: 'nm', regionName: '呼伦贝尔市', regionCode: '150700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bynr', parentId: 'nm', regionName: '巴彦淖尔市', regionCode: '150800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wlc', parentId: 'nm', regionName: '乌兰察布市', regionCode: '150900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xa', parentId: 'nm', regionName: '兴安盟', regionCode: '152200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xlgl', parentId: 'nm', regionName: '锡林郭勒盟', regionCode: '152500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'als', parentId: 'nm', regionName: '阿拉善盟', regionCode: '152900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 华中地区
  // 河南省
  { regionId: 'zz', parentId: 'henan', regionName: '郑州市', regionCode: '410100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'kf', parentId: 'henan', regionName: '开封市', regionCode: '410200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ly', parentId: 'henan', regionName: '洛阳市', regionCode: '410300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pds', parentId: 'henan', regionName: '平顶山市', regionCode: '410400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ay', parentId: 'henan', regionName: '安阳市', regionCode: '410500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hb', parentId: 'henan', regionName: '鹤壁市', regionCode: '410600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xx', parentId: 'henan', regionName: '新乡市', regionCode: '410700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jz', parentId: 'henan', regionName: '焦作市', regionCode: '410800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'py', parentId: 'henan', regionName: '濮阳市', regionCode: '410900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xc', parentId: 'henan', regionName: '许昌市', regionCode: '411000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lh', parentId: 'henan', regionName: '漯河市', regionCode: '411100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'smx', parentId: 'henan', regionName: '三门峡市', regionCode: '411200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ny', parentId: 'henan', regionName: '南阳市', regionCode: '411300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sq_henan', parentId: 'henan', regionName: '商丘市', regionCode: '411400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xy_henan', parentId: 'henan', regionName: '信阳市', regionCode: '411500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zk', parentId: 'henan', regionName: '周口市', regionCode: '411600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zmd', parentId: 'henan', regionName: '驻马店市', regionCode: '411700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jy', parentId: 'henan', regionName: '济源市', regionCode: '419001', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 湖北省
  { regionId: 'wh_hb', parentId: 'hubei', regionName: '武汉市', regionCode: '420100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hs_hb', parentId: 'hubei', regionName: '黄石市', regionCode: '420200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sy', parentId: 'hubei', regionName: '十堰市', regionCode: '420300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yc_hb', parentId: 'hubei', regionName: '宜昌市', regionCode: '420500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xy', parentId: 'hubei', regionName: '襄阳市', regionCode: '420600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ez', parentId: 'hubei', regionName: '鄂州市', regionCode: '420700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jm_hb', parentId: 'hubei', regionName: '荆门市', regionCode: '420800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xg', parentId: 'hubei', regionName: '孝感市', regionCode: '420900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jz_hb', parentId: 'hubei', regionName: '荆州市', regionCode: '421000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hg', parentId: 'hubei', regionName: '黄冈市', regionCode: '421100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xn_hb', parentId: 'hubei', regionName: '咸宁市', regionCode: '421200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz_hb', parentId: 'hubei', regionName: '随州市', regionCode: '421300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'es', parentId: 'hubei', regionName: '恩施土家族苗族自治州', regionCode: '422800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 湖南省
  { regionId: 'cs', parentId: 'hunan', regionName: '长沙市', regionCode: '430100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zz_hunan', parentId: 'hunan', regionName: '株洲市', regionCode: '430200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xt_hunan', parentId: 'hunan', regionName: '湘潭市', regionCode: '430300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hy', parentId: 'hunan', regionName: '衡阳市', regionCode: '430400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sy_hunan', parentId: 'hunan', regionName: '邵阳市', regionCode: '430500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yy', parentId: 'hunan', regionName: '岳阳市', regionCode: '430600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cd_hunan', parentId: 'hunan', regionName: '常德市', regionCode: '430700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zjj', parentId: 'hunan', regionName: '张家界市', regionCode: '430800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ys', parentId: 'hunan', regionName: '益阳市', regionCode: '430900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cz_hunan', parentId: 'hunan', regionName: '郴州市', regionCode: '431000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yz_hunan', parentId: 'hunan', regionName: '永州市', regionCode: '431100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hh', parentId: 'hunan', regionName: '怀化市', regionCode: '431200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ld', parentId: 'hunan', regionName: '娄底市', regionCode: '431300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xx_hunan', parentId: 'hunan', regionName: '湘西土家族苗族自治州', regionCode: '433100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 西南地区
  // 重庆市
  { regionId: 'cq_c', parentId: 'cq', regionName: '重庆市', regionCode: '500100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 四川省
  { regionId: 'cd', parentId: 'sc', regionName: '成都市', regionCode: '510100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zg', parentId: 'sc', regionName: '自贡市', regionCode: '510300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pzh', parentId: 'sc', regionName: '攀枝花市', regionCode: '510400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lz_sc', parentId: 'sc', regionName: '泸州市', regionCode: '510500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dy', parentId: 'sc', regionName: '德阳市', regionCode: '510600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'my', parentId: 'sc', regionName: '绵阳市', regionCode: '510700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gy_sc', parentId: 'sc', regionName: '广元市', regionCode: '510800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sn', parentId: 'sc', regionName: '遂宁市', regionCode: '510900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nj', parentId: 'sc', regionName: '内江市', regionCode: '511000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ls_sc', parentId: 'sc', regionName: '乐山市', regionCode: '511100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nc_sc', parentId: 'sc', regionName: '南充市', regionCode: '511300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ms', parentId: 'sc', regionName: '眉山市', regionCode: '511400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yb', parentId: 'sc', regionName: '宜宾市', regionCode: '511500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ga', parentId: 'sc', regionName: '广安市', regionCode: '511600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dz_sc', parentId: 'sc', regionName: '达州市', regionCode: '511700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ya', parentId: 'sc', regionName: '雅安市', regionCode: '511800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bz', parentId: 'sc', regionName: '巴中市', regionCode: '511900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zy_sc', parentId: 'sc', regionName: '资阳市', regionCode: '512000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'aba', parentId: 'sc', regionName: '阿坝藏族羌族自治州', regionCode: '513200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ganzi', parentId: 'sc', regionName: '甘孜藏族自治州', regionCode: '513300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'liangshan', parentId: 'sc', regionName: '凉山彝族自治州', regionCode: '513400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 贵州省
  { regionId: 'gy', parentId: 'gz', regionName: '贵阳市', regionCode: '520100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lps', parentId: 'gz', regionName: '六盘水市', regionCode: '520200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zy_gz', parentId: 'gz', regionName: '遵义市', regionCode: '520300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'as', parentId: 'gz', regionName: '安顺市', regionCode: '520400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bj', parentId: 'gz', regionName: '毕节市', regionCode: '520500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tr', parentId: 'gz', regionName: '铜仁市', regionCode: '520600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qxn', parentId: 'gz', regionName: '黔西南布依族苗族自治州', regionCode: '522300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qdn', parentId: 'gz', regionName: '黔东南苗族侗族自治州', regionCode: '522600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qn', parentId: 'gz', regionName: '黔南布依族苗族自治州', regionCode: '522700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 云南省
  { regionId: 'km', parentId: 'yn', regionName: '昆明市', regionCode: '530100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qj', parentId: 'yn', regionName: '曲靖市', regionCode: '530300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yx', parentId: 'yn', regionName: '玉溪市', regionCode: '530400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bs', parentId: 'yn', regionName: '保山市', regionCode: '530500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zt', parentId: 'yn', regionName: '昭通市', regionCode: '530600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lijiang', parentId: 'yn', regionName: '丽江市', regionCode: '530700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pe', parentId: 'yn', regionName: '普洱市', regionCode: '530800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lc', parentId: 'yn', regionName: '临沧市', regionCode: '530900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cx', parentId: 'yn', regionName: '楚雄彝族自治州', regionCode: '532300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hh', parentId: 'yn', regionName: '红河哈尼族彝族自治州', regionCode: '532500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ws', parentId: 'yn', regionName: '文山壮族苗族自治州', regionCode: '532600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xsbn', parentId: 'yn', regionName: '西双版纳傣族自治州', regionCode: '532800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dl', parentId: 'yn', regionName: '大理白族自治州', regionCode: '532900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dh', parentId: 'yn', regionName: '德宏傣族景颇族自治州', regionCode: '533100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nj', parentId: 'yn', regionName: '怒江傈僳族自治州', regionCode: '533300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dq', parentId: 'yn', regionName: '迪庆藏族自治州', regionCode: '533400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 西藏自治区
  { regionId: 'lasa', parentId: 'xz', regionName: '拉萨市', regionCode: '540100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'rkz', parentId: 'xz', regionName: '日喀则市', regionCode: '540200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cd_xz', parentId: 'xz', regionName: '昌都市', regionCode: '540300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lz_xz', parentId: 'xz', regionName: '林芝市', regionCode: '540400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sn_xz', parentId: 'xz', regionName: '山南市', regionCode: '540500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'nq', parentId: 'xz', regionName: '那曲市', regionCode: '540600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'al', parentId: 'xz', regionName: '阿里地区', regionCode: '542500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 西北地区
  // 陕西省
  { regionId: 'xa', parentId: 'shaanxi', regionName: '西安市', regionCode: '610100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tc', parentId: 'shaanxi', regionName: '铜川市', regionCode: '610200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bj', parentId: 'shaanxi', regionName: '宝鸡市', regionCode: '610300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'xy', parentId: 'shaanxi', regionName: '咸阳市', regionCode: '610400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wn', parentId: 'shaanxi', regionName: '渭南市', regionCode: '610500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ya', parentId: 'shaanxi', regionName: '延安市', regionCode: '610600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hz', parentId: 'shaanxi', regionName: '汉中市', regionCode: '610700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yl', parentId: 'shaanxi', regionName: '榆林市', regionCode: '610800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ak', parentId: 'shaanxi', regionName: '安康市', regionCode: '610900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sl', parentId: 'shaanxi', regionName: '商洛市', regionCode: '611000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 甘肃省
  { regionId: 'lz', parentId: 'gs', regionName: '兰州市', regionCode: '620100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jyg', parentId: 'gs', regionName: '嘉峪关市', regionCode: '620200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jc', parentId: 'gs', regionName: '金昌市', regionCode: '620300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'by', parentId: 'gs', regionName: '白银市', regionCode: '620400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ts', parentId: 'gs', regionName: '天水市', regionCode: '620500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ww', parentId: 'gs', regionName: '武威市', regionCode: '620600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zy', parentId: 'gs', regionName: '张掖市', regionCode: '620700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pl', parentId: 'gs', regionName: '平凉市', regionCode: '620800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jq', parentId: 'gs', regionName: '酒泉市', regionCode: '620900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qy', parentId: 'gs', regionName: '庆阳市', regionCode: '621000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dx', parentId: 'gs', regionName: '定西市', regionCode: '621100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ln', parentId: 'gs', regionName: '陇南市', regionCode: '621200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'lx', parentId: 'gs', regionName: '临夏回族自治州', regionCode: '622900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gn', parentId: 'gs', regionName: '甘南藏族自治州', regionCode: '623000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 青海省
  { regionId: 'xn', parentId: 'qh', regionName: '西宁市', regionCode: '630100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hd', parentId: 'qh', regionName: '海东市', regionCode: '630200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hbt', parentId: 'qh', regionName: '海北藏族自治州', regionCode: '632200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hn', parentId: 'qh', regionName: '黄南藏族自治州', regionCode: '632300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hainan', parentId: 'qh', regionName: '海南藏族自治州', regionCode: '632500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gl', parentId: 'qh', regionName: '果洛藏族自治州', regionCode: '632600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ys', parentId: 'qh', regionName: '玉树藏族自治州', regionCode: '632700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hxc', parentId: 'qh', regionName: '海西蒙古族藏族自治州', regionCode: '632800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 宁夏回族自治区
  { regionId: 'yc', parentId: 'nx', regionName: '银川市', regionCode: '640100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sz', parentId: 'nx', regionName: '石嘴山市', regionCode: '640200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'wz', parentId: 'nx', regionName: '吴忠市', regionCode: '640300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'gy', parentId: 'nx', regionName: '固原市', regionCode: '640400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'zw', parentId: 'nx', regionName: '中卫市', regionCode: '640500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 新疆维吾尔自治区
  { regionId: 'wlmq', parentId: 'xj', regionName: '乌鲁木齐市', regionCode: '650100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'klmy', parentId: 'xj', regionName: '克拉玛依市', regionCode: '650200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tlf', parentId: 'xj', regionName: '吐鲁番市', regionCode: '650400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hms', parentId: 'xj', regionName: '哈密市', regionCode: '650500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cjs', parentId: 'xj', regionName: '昌吉回族自治州', regionCode: '652300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bts', parentId: 'xj', regionName: '博尔塔拉蒙古自治州', regionCode: '652700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'byl', parentId: 'xj', regionName: '巴音郭楞蒙古自治州', regionCode: '652800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'aks', parentId: 'xj', regionName: '阿克苏地区', regionCode: '652900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ksl', parentId: 'xj', regionName: '克孜勒苏柯尔克孜自治州', regionCode: '653000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ks', parentId: 'xj', regionName: '喀什地区', regionCode: '653100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ht', parentId: 'xj', regionName: '和田地区', regionCode: '653200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yl', parentId: 'xj', regionName: '伊犁哈萨克自治州', regionCode: '654000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tc', parentId: 'xj', regionName: '塔城地区', regionCode: '654200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'alt', parentId: 'xj', regionName: '阿勒泰地区', regionCode: '654300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 东北地区
  // 辽宁省
  { regionId: 'sy', parentId: 'ln', regionName: '沈阳市', regionCode: '210100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dl', parentId: 'ln', regionName: '大连市', regionCode: '210200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'as', parentId: 'ln', regionName: '鞍山市', regionCode: '210300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fs', parentId: 'ln', regionName: '抚顺市', regionCode: '210400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bx', parentId: 'ln', regionName: '本溪市', regionCode: '210500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dd', parentId: 'ln', regionName: '丹东市', regionCode: '210600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jz', parentId: 'ln', regionName: '锦州市', regionCode: '210700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yk', parentId: 'ln', regionName: '营口市', regionCode: '210800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'fx', parentId: 'ln', regionName: '阜新市', regionCode: '210900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ly', parentId: 'ln', regionName: '辽阳市', regionCode: '211000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'pj', parentId: 'ln', regionName: '盘锦市', regionCode: '211100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'tl', parentId: 'ln', regionName: '铁岭市', regionCode: '211200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'cy', parentId: 'ln', regionName: '朝阳市', regionCode: '211300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hld', parentId: 'ln', regionName: '葫芦岛市', regionCode: '211400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 吉林省
  { regionId: 'cc', parentId: 'jl', regionName: '长春市', regionCode: '220100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jl_city', parentId: 'jl', regionName: '吉林市', regionCode: '220200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sp', parentId: 'jl', regionName: '四平市', regionCode: '220300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ly', parentId: 'jl', regionName: '辽源市', regionCode: '220400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'th', parentId: 'jl', regionName: '通化市', regionCode: '220500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'bs', parentId: 'jl', regionName: '白山市', regionCode: '220600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sy_jl', parentId: 'jl', regionName: '松原市', regionCode: '220700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'baicheng', parentId: 'jl', regionName: '白城市', regionCode: '220800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yb', parentId: 'jl', regionName: '延边朝鲜族自治州', regionCode: '222400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  // 黑龙江省
  { regionId: 'hrb', parentId: 'hlj', regionName: '哈尔滨市', regionCode: '230100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qqhr', parentId: 'hlj', regionName: '齐齐哈尔市', regionCode: '230200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'jx', parentId: 'hlj', regionName: '鸡西市', regionCode: '230300', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hg', parentId: 'hlj', regionName: '鹤岗市', regionCode: '230400', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sys', parentId: 'hlj', regionName: '双鸭山市', regionCode: '230500', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dq', parentId: 'hlj', regionName: '大庆市', regionCode: '230600', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'yc', parentId: 'hlj', regionName: '伊春市', regionCode: '230700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'ms', parentId: 'hlj', regionName: '佳木斯市', regionCode: '230800', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'qth', parentId: 'hlj', regionName: '七台河市', regionCode: '230900', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mdj', parentId: 'hlj', regionName: '牡丹江市', regionCode: '231000', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'hh', parentId: 'hlj', regionName: '黑河市', regionCode: '231100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'sh', parentId: 'hlj', regionName: '绥化市', regionCode: '231200', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'dxal', parentId: 'hlj', regionName: '大兴安岭地区', regionCode: '232700', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  
  // Cities - 特别行政区
  { regionId: 'hk_c', parentId: 'hk', regionName: '香港特别行政区', regionCode: '810100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
  { regionId: 'mo_c', parentId: 'mo', regionName: '澳门特别行政区', regionCode: '820100', regionLevel: RegionLevel.CITY, status: DictStatus.ENABLED, isSystem: true, createTime: now },
];

