import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { modelLibrary, loadModelLibrary } from './models.js';

const canvas=document.querySelector('#scene');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050b14);scene.fog=new THREE.FogExp2(0x07111f,.012);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,300);camera.position.set(0,38,72);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<900?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.outputColorSpace=THREE.SRGBColorSpace;
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.target.set(0,1,0);controls.maxPolarAngle=Math.PI*.49;controls.minDistance=15;controls.maxDistance=120;
scene.add(new THREE.HemisphereLight(0xa6ddff,0x06101a,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-25,45,30);sun.castShadow=true;scene.add(sun);const rim=new THREE.DirectionalLight(0x21d4ff,1.5);rim.position.set(35,20,-30);scene.add(rim);
const world=new THREE.Group();scene.add(world);const animated=[];const clickable=[];
const floor=new THREE.Mesh(new THREE.PlaneGeometry(130,85),new THREE.MeshStandardMaterial({color:0x091521,roughness:.86}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor);const grid=new THREE.GridHelper(130,65,0x1b6681,0x15364a);grid.material.opacity=.3;grid.material.transparent=true;world.add(grid);
const stations=[
{id:'stamping',name:'冲压车间',en:'STAMPING',p:[-36,0,-18],c:0x3fa9ff,cam:[-49,25,7],target:[-36,2,-18]},
{id:'welding',name:'焊装车间',en:'BODY SHOP',p:[-12,0,-18],c:0x15d8ff,cam:[-25,22,2],target:[-12,2,-18]},
{id:'painting',name:'涂装车间',en:'PAINT SHOP',p:[13,0,-18],c:0xa883ff,cam:[2,23,2],target:[13,2,-18]},
{id:'assembly',name:'总装车间',en:'ASSEMBLY',p:[37,0,-18],c:0x39efaa,cam:[25,23,4],target:[37,2,-18]},
{id:'quality',name:'质量检测',en:'QUALITY',p:[26,0,15],c:0xffbd4a,cam:[15,21,30],target:[26,2,15]},
{id:'logistics',name:'智能物流',en:'LOGISTICS',p:[-21,0,15],c:0xff657a,cam:[-34,21,30],target:[-21,2,15]}];
function clone(key,parent,pos=[0,0,0],scale=1,rot=0,station=''){const x=modelLibrary.get(key).clone(true);x.position.set(...pos);x.rotation.y=rot;Array.isArray(scale)?x.scale.set(...scale):x.scale.setScalar(scale);x.userData.stationId=station;x.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.stationId=station;if(o.material)o.material=o.material.clone();clickable.push(o)}});parent.add(x);return x}
function conveyor(g){clone('conveyor',g,[-4.2,0,0],1,0,g.userData.stationId);clone('conveyor',g,[4.2,0,0],1,0,g.userData.stationId)}
function robot(g,x,z,r=0,s=.55){const m=clone('robot',g,[x,0,z],s,r,g.userData.stationId);animated.push({type:'robot',s:m.getObjectByName('Robot_ShoulderPivot'),e:m.getObjectByName('Robot_ElbowPivot'),w:m.getObjectByName('Robot_WristPivot'),o:Math.random()*6})}
function zone(st){const g=new THREE.Group();g.position.set(...st.p);g.userData.stationId=st.id;world.add(g);const base=new THREE.Mesh(new THREE.BoxGeometry(20,.18,17),new THREE.MeshStandardMaterial({color:0x102638,emissive:st.c,emissiveIntensity:.05,metalness:.25,roughness:.7}));base.position.y=.08;base.userData.stationId=st.id;g.add(base);clickable.push(base);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(20.2,.23,17.2)),new THREE.LineBasicMaterial({color:st.c,transparent:true,opacity:.45}));edge.position.y=.12;g.add(edge);conveyor(g);if(st.id==='stamping')[-5,0,5].forEach((x,i)=>{const p=clone('press',g,[x,0,-2],.67,0,st.id);animated.push({type:'press',r:p.getObjectByName('Press_Ram'),f:p.getObjectByName('Press_Flywheel'),o:i})});if(st.id==='welding'){[-6,-2,2,6].forEach((x,i)=>robot(g,x,i%2?2.7:-2.7,i%2?Math.PI:0));clone('car',g,[-1,.1,0],.75,0,st.id)}if(st.id==='painting'){clone('booth',g,[0,0,0],[1.03,.9,1],0,st.id);[-5,-1.7,1.7,5].forEach((x,i)=>robot(g,x,i%2?2.3:-2.3,i%2?Math.PI:0,.46));clone('car',g,[-2,.1,0],.72,0,st.id)}if(st.id==='assembly'){clone('car',g,[0,.1,0],.78,0,st.id);robot(g,-5,-2.7,0);robot(g,5,2.7,Math.PI);clone('lifter',g,[0,0,0],[2,.92,1],0,st.id)}if(st.id==='quality'){clone('car',g,[-1,.1,0],.78,0,st.id);[-5,0,5].forEach((x,i)=>{const q=clone('quality',g,[x,0,0],.88,0,st.id);animated.push({type:'scan',m:q.getObjectByName('Quality_ScannerBeam'),o:i})})}if(st.id==='logistics'){for(let i=0;i<4;i++){const a=clone('agv',g,[-7+i*4,0,0],.68,0,st.id);animated.push({type:'agv',m:a,o:i/4})}[-5,0,5].forEach(x=>[-3,3].forEach(z=>{for(let y=1;y<5;y++){const r=new THREE.Mesh(new THREE.BoxGeometry(3.5,.15,1.2),new THREE.MeshStandardMaterial({color:0x3c5360,metalness:.7}));r.position.set(x,y,z);g.add(r)}}))}}
function select(st){document.querySelectorAll('.process-item').forEach(b=>b.classList.toggle('active',b.dataset.id===st.id));document.querySelector('#stationTitle').textContent=st.name;document.querySelector('#stationDescription').textContent=`${st.name}真实三维设备运行视图，支持旋转、缩放与工艺聚焦。`;camera.position.set(...st.cam);controls.target.set(...st.target)}
const list=document.querySelector('#processList');stations.forEach((st,i)=>{const b=document.createElement('button');b.className='process-item'+(i===1?' active':'');b.dataset.id=st.id;b.style.setProperty('--item-color','#'+st.c.toString(16).padStart(6,'0'));b.innerHTML=`<span class="process-index">${String(i+1).padStart(2,'0')}</span><span class="process-name"><strong>${st.name}</strong><small>${st.en}</small></span><span class="process-rate">运行</span>`;b.onclick=()=>select(st);list.appendChild(b)});
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();canvas.addEventListener('click',ev=>{const r=canvas.getBoundingClientRect();mouse.set((ev.clientX-r.left)/r.width*2-1,-(ev.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(clickable,true).find(x=>x.object.userData.stationId);if(hit){const st=stations.find(s=>s.id===hit.object.userData.stationId);if(st)select(st)}});
function frame(ms){requestAnimationFrame(frame);const t=ms*.001;animated.forEach(a=>{if(a.type==='robot'&&a.s){a.s.rotation.z=-.2+.35*Math.sin(t+a.o);a.e.rotation.z=-.45+.45*Math.sin(t*1.4+a.o);a.w.rotation.y=t*1.5}if(a.type==='press'&&a.r){a.r.position.y=3.72-1.45*Math.max(0,Math.sin(t*1.8+a.o));if(a.f)a.f.rotation.z=t*2}if(a.type==='scan'&&a.m)a.m.position.x=.45*Math.sin(t*1.5+a.o);if(a.type==='agv')a.m.position.set(7*Math.sin(t*.55+a.o*6.28),0,2.2*Math.cos(t*.55+a.o*6.28))});controls.update();renderer.render(scene,camera)}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelector('#resetBtn').onclick=()=>{camera.position.set(0,38,72);controls.target.set(0,1,0)};document.querySelector('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false}),1000);
try{await loadModelLibrary();stations.forEach(zone);select(stations[1]);document.querySelector('#loading small').textContent='三维模型加载完成';setTimeout(()=>document.querySelector('#loading').classList.add('hidden'),350);requestAnimationFrame(frame)}catch(err){console.error(err);document.querySelector('#loading strong').textContent='三维模型初始化失败';document.querySelector('#loading small').textContent=err.message}
